[package]
name = "quaturn"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ToothlessBrush/Quaturn"
description = "A 3D game engine written in Rust"
license = "MIT"
authors = ["ToothlessBrush <johnklein514@gmail.com."]
readme = "README.md"
keywords = ["3d", "game", "engine", "gamedev", "graphics"]
categories = ["game-engines", "graphics"]

include = [
    "res/primitives/**/*",
    "res/shaders/**/*",
    "**/*.rs",
    "cargo.toml"
]

exclude = [
    "res/models/**/*"
]

[lib]
name = "quaturn"
path = "src/lib.rs"


[dependencies]
clipboard = "0.5.0"
colored = "2.1.0"
egui_gl_glfw = "0.1.5"
gl = "0.14.0"
gltf = { version = "1.4.1", features = ["KHR_materials_pbrSpecularGlossiness"] }
nalgebra-glm = "0.18.0"
stb_image = "0.3.0"
