[package]
name = "quaturn"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard = "0.5.0"
colored = "2.1.0"
egui_gl_glfw = "0.1.5"
gl = "0.14.0"
gltf = "1.4.1"
nalgebra-glm = "0.18.0"
stb_image = "0.3.0"

